import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/navBar";
import { routes } from "./routesMapping";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar routes={routes} />
        {children}
        <div id="portal" />
      </body>
    </html>
  );
}
