import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/navBar";
import { routes } from "./routesMapping";
import Provider from "./context/provider";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Provider>
          <NavBar routes={routes} showRoutes={true} />
          {children}
          <div id="portal" />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
